### ISSUE TITLE
Many thanks

### ISSUE THREAD

**Issue by IvanLiuTW** [justamad/PyMoCapViewer#1]
I've found many ways to plot mocap data as 3D animation for three days, and using matplotlib, ipyvolume but all in vain. However, **your PyMoCapViewer is amazing**!!!👏🏻👏🏻👏🏻 Super easy to use, and the result is also what I need. Thank you so much for sharing it.

**Comment by justamad** [comment]
Hey Ivan, many thanks for your feedback! I'm glad to hear that this project is helpful to you. I started this off when I was searching for a solution myself for days as well. Is there something that we could optimize to make the project better?

**Comment by IvanLiuTW** [comment]
Hey Justamad, thanks for the reply. Umm..., I think everything is fine, because I am not very good at 3D plotting.😅 I am just wondering, my animation playing speed seem to be a little bit slow, so is there any way to improve it?

By the way, since my the points got by MoCap system is different from your default skeleton, I made a new one by revising one of the skeleton .py files and it also worked. It's really easy to use!😃

**Comment by justamad** [comment]
Hey Ivan, you can control the playing speed with the 'sampling_frequency' (in fps) argument in the constructor of the viewer. It's probably not 100% accurate but should be good enough.

A planned task is to make the interface for the skeleton definition even easier. But it is great to hear that you were able to adjust the skeleton definition to your needs. :D

**Comment by IvanLiuTW** [comment]
Hello Justamad, sorry for the late reply. I did notice the parameter, sampling_frequency, and I adjusted it but it didn't seem to work. 😅 

Since I seldom process mocap data, I don't see many of them. However, from a programming view, I think it is easy to follow the default skeleton definitions, make one copy of them, and modify it to suit the needs.

**Comment by IvanLiuTW** [comment]
Hello Justamad, 

Sorry, a question about the MocapViewer. If I want to make the video show the extra information like the current frame or time, is it possible to do that?

**Comment by justamad** [comment]
Hello Ivan,

I suppose this should be possible. It's a nice feature that I'd like to include as well. I'll look into that when I have more time.

**Comment by IvanLiuTW** [comment]
Hello Justamad,

Thank you~
